### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by gras64**

### CODE REVIEW

**Comment by btotharye** [comment]
test this please

**Comment by btotharye** [comment]
test this please

**Comment by btotharye** [comment]
@gras64 are you familiar with how to add tests in?  If not I can do it but wouldn't mind having the german tests setup for this before I merge it, let me know if you don't know how to do it I can do it after I merge it in.

More info on setting up the test can be found at https://mycroft.ai/documentation/skills/automatic-testing/ and I have a example in english at https://github.com/Geeked-Out-Solutions/mycroft-skill-today-in-history/blob/master/test/intent/sample1.intent.json

**Comment by btotharye** [comment]
test this please

**Comment by gras64** [comment]
I have no idea how to create a test file. in this skill there is currently also language support in the issue.

**Pull request merged**
